### PR TITLE
Quantile gene removal 

### PR DESCRIPTION
**Pull request by nifets**
Added functionality for removing top level genes when computing TAI profiles, to see how much this perturbation disturbs the TAI pattern. This can be done by either removing the most expressed genes (via `TopExpressionGenes()`) or the genes with the highest expression variance (via `TopVarianceGenes()`).

Based on these functions, the function`PlotSignatureGeneQuantiles` can be used to compare the TAI signals for different removal thresholds.

Screenshot 2024-11-20 at 17 57 05

It relies internally on `PlotSignatureMultiple`, which is a generic way to overlay the TAI profiles for different expression sets on the same axes. This might be of interest also for visualising GATAI gene removal.

### CODE REVIEW

**Comment by nifets** [comment]
the standard deviations for the profiles i show above are suspiciously small, i'll need to investigate that

**Comment by nifets** [comment]
this is the output of `PlotSignatureMultiple`, which seems sensible
Screenshot 2024-11-20 at 18 02 20

**Comment by HajkD** [comment]
This is absolutely brilliant @nifets :)

Thank you so much for adding these new functions. 

I completely agree that this overlap style should also be used for plotting GATAI gene removal. @filipamc19 would this be something, you would be interested in looking into? 

As for the confidence intervals from the FlatLineTests, I agree that this is quite strange, they do seem to be too narrow. Maybe we can double-check this?

Also your insight on removing the `bootMatrix()` computation seems correct. Please feel free to look into this and remove this redundant computation also from the other `Plot*` functions.

Would it also be possible to have a look at your `config.log` file? It seems like there is no need to push this to the repo since it may create merging conflicts.

Once you had another go at this, please feel free to send an updated PR and I will merge everything:)

Many thanks,
Hajk

**Comment by nifets** [comment]
Thank you for the comments @HajkD. They should be addressed now.
Here is the updated plot with corrected stddev bands:
Screenshot 2024-11-21 at 11 43 37

Note how removing top 20% expressed genes yields a really narrow null distribution. I found that quite surprising.

**Comment by nifets** [comment]
Screenshot 2024-11-21 at 11 47 47
this is the flat line test for quantile 80% top-expressed genes

**Comment by HajkD** [comment]
Hi @nifets 

This looks fantastic now, thank you so much for these new commts!

I will merge everything now and very much look forward to working extensively on myTAI2 with you :)

Cheers,
Hajk

**Comment by filipamc19** [comment]
Hi @HajkD and @nifets,

Apologies for the delayed response but today was a bit chaotic at the company, and I only just saw the message today.

I completely agree that overlapping the patterns for GATAI gene removal is a great idea, and I’m very interested in exploring it further!

Do you think it would make more sense to add a new function specifically for this, or should I modify SignatureGATAIGeneRemoval() to plot a single overlapping plot instead of the current four separate plots?

Looking forward to hearing both your thoughts!

**Comment by filipamc19** [comment]
Hi @HajkD,

Thank you for the suggestion, I think it’s a great idea! I’ll work on implementing it and will submit a pull request as soon as it’s ready.

Best wishes,
Filipa

**Comment by nifets** [comment]
@HajkD just wanted to quickly show these plots of how the null distribution of the flat line test changes as you remove top genes:
Screenshot 2024-11-21 at 18 55 04
Screenshot 2024-11-21 at 18 54 57

Also, with GATAI removed genes:

Screenshot 2024-11-21 at 19 01 55

Screenshot 2024-11-21 at 19 01 39

Sorry this plot is a bit too crowded but hope you see the point.
Since we only remove 100 genes with GATAI, the null distribution doesn't change much here.

But anyway, I find it interesting how much this null distribution changes when you only remove 10% or 20% of the genes. I also looked at the age distribution of these removed genes and if anything they are a bit biased towards PS1, resulting in the remaining genes actually having a more diverse distribution of gene ages than the original set of genes. Hence the trend of average TAI going up as you remove more and more top genes.

Interestingly also, whether you select top genes by their total expression or by the variance of their expression, the result is largely the same. This is because about 90% of the genes of top expression also feature top variance of expression. 

I guess the reason why the null distribution gets narrower is just because the remaining gene profiles just have a lower impact on the overall TAI due to them having low variance.

**Pull request merged**
