### PR TITLE
`PlotSignatureTransformed()` function added

### PR DESCRIPTION
**Pull request by LotharukpongJS**
Implemented `PlotSignatureTransformed()` and some minor changes:
- `PlotSignatureTransformed()`, which complements `PlotSignature()` and `tfStability()`, has now been implemented.
- `gridExtra::grid.arrange()` is replaced with `ggpubr::ggarrange()`.
- `PlotSignature()` now also works with the `TestStatistic = "LateConservationTest"`, first implemented in #11 . This lack of functionality had been previously overlooked.
- Rebuilt the package website with `pkgdown::build_site()`.
- Fixed the issues with `devtools::check()` after #17 
- Addressed #16 (adding p-values as subtitles).
- Updated some of the documentation, including the pseudocount parameter description for 

For `PlotSignatureTransformed()`:

```r
PlotSignatureTransformed(ExpressionSet = PhyloExpressionSetExample,
                         TestStatistic = "ReductiveHourglassTest",
                         transforms = c("log2", "sqrt", "none", “vst”, “log”, “rank”, “squared"),
                         modules = list(early = 1:2, mid = 3:5, late = 6:7))
```
image

### CODE REVIEW

**Comment by LotharukpongJS** [comment]
Removed non-standard files/directories.

**Comment by LotharukpongJS** [comment]
Removed non-standard files/directories.

**Comment by LotharukpongJS** [comment]
Removed non-standard files/directories.

**Comment by HajkD** [comment]
Wow!!! Brilliant work, @LotharukpongJS!

Looks perfect to me!

**Pull request merged**
