### PR TITLE
improved fit, added ks-test

### PR DESCRIPTION
**Pull request by lavakin**
Removing outliers and selecting the best fit.
Added ks-test (computed on the filtered data) to the output statistics.

### CODE REVIEW

**Comment by HajkD** [comment]
Hi @lavakin 

Thank you so much for pushing this forward!

Everything looks great and ready to me!

Just two little edits:

1) Would it be possible to use `message()` instead of `print()` in all cases.
2) Since vector/array indexing in R starts with `1`, would it be possible to double check that `0` indexing doesn't cause any unwanted/unforeseen issues? 

With many thanks,
Hajk

**Comment by lavakin** [comment]
Done :)

**Comment by HajkD** [comment]
Brilliant! Thank you so much :)

**Comment by LotharukpongJS** [comment]
Hi @HajkD and @lavakin ,

Nice additions! In terms of testing the new functionalities, have you run `devtools::check()`?

Best,
Sodai

**Pull request merged**
